name: Validate

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
      - 'library.json'
      - '*.lua'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: OmiLib
    - name: Checkout luabun
      uses: actions/checkout@v4
      with:
        path: luabun
        repository: omarkmu/luabun
    - name: Install luabun
      run: cd luabun && npm i && cd ..
    - name: Build bundle
      run: node luabun create OmiLib --all
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Lua 5.1
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: '5.1.5'
    - name: Set up LuaRocks
      uses: leafo/gh-actions-luarocks@v4
      with:
        luaRocksVersion: "3.11.0"
    - name: Set up Busted
      run: luarocks install busted
    - name: Run tests
      run: busted -v test -p .lua -m ./src/?.lua
